CREATE TABLE IF NOT EXISTS `claramente_recache_urls` (
    `ID` int NOT NULL AUTO_INCREMENT,
    `URL` varchar(2083) NOT NULL,
    `URL_HASH` varchar(32) NOT NULL,
    `STATUS` varchar(16) NOT NULL DEFAULT 'wait',
    `RESPONSE_CODE` int DEFAULT NULL,
    `REQUEST_TIME_MS` int DEFAULT NULL,
    `SITE_ID` varchar(12) DEFAULT NULL,
    `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `URL_HASH` (`URL_HASH`) USING BTREE,
    KEY `RESPONSE_CODE` (`RESPONSE_CODE`) USING BTREE,
    KEY `STATUS` (`STATUS`) USING BTREE,
    KEY `SITE_ID` (`SITE_ID`) USING BTREE
);